### ISSUE TITLE
Problem 2: Unit Testing With Frameworks (Issue #2)

### ISSUE THREAD

**Issue by lilyicecream** [drod0942/Homework-5_Unit-Testing#2]

**Comment by drod0942** [comment]
Repeat the implementation of the same unit tests as for problem 1 but this time with Python’s pytest framework (https://docs.pytest.org/). The test functionality and results should be the same as for the script you wrote for problem 1. The output should be the standard output of pytest. 

Please provide a readme with an explanation how we can set up and run your unit tests.
