### ISSUE TITLE
Problem 5: Set up CI for Front End Testing (issue#5)

### ISSUE THREAD

**Issue by drod0942** [drod0942/Homework-5_Unit-Testing#6]

**Comment by lilyicecream** [comment]
Using GitHub Actions (https://docs.github.com/en/actions/), set up continuous integration (CI) for your frontend unit tests from problem 4 inside the GitHub repo that holds your frontend code from homework 3. Once set up, your CI will run all unit tests when push code changes to check the integrity of your codebase.
